name: pawfect_bites
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  tflite_flutter: ^0.11.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dog.jpg
    - assets/images/cat.jpg
    - assets/images/bird.jpg
    - assets/images/cow.jpg
    - assets/images/doctor.png

    - assets/images/mani.jpg
    - assets/images/allan.jpg
    - assets/images/somesh.jpg

    - assets/databases/animalhealth.db

    - assets/models/poultry_disease_model.tflite
    - assets/models/cat_disease_model.tflite
    - assets/models/dog_disease_model.tflite
